-- STAT 코드 라벨 추가 (패시브 스탯 등에 사용)
INSERT IGNORE INTO common_codes (code_type, code) VALUES
  ('STAT', 'attack_per'),
  ('STAT', 'elementAttack_per'),
  ('STAT', 'hp_per'),
  ('STAT', 'defense_per'),
  ('STAT', 'shield_per'),
  ('STAT', 'damage'),
  ('STAT', 'skillEfficiency'),
  ('STAT', 'skillDuration'),
  ('STAT', 'skillRange'),
  ('STAT', 'skillDmg'),
  ('STAT', 'skillIntensity'),
  ('STAT', 'weaponAttack_per'),
  ('STAT', 'slashAttack_per'),
  ('STAT', 'spikeAttack_per'),
  ('STAT', 'smashAttack_per'),
  ('STAT', 'weaponDmg'),
  ('STAT', 'explosionRange'),
  ('STAT', 'beamLength'),
  ('STAT', 'reloadSpeed'),
  ('STAT', 'critRate'),
  ('STAT', 'critDamage'),
  ('STAT', 'attackSpeed'),
  ('STAT', 'attackRange'),
  ('STAT', 'triggerProbability'),
  ('STAT', 'multishot'),
  ('STAT', 'magCapacity'),
  ('STAT', 'maxAmmo'),
  ('STAT', 'ammoConversionRate'),
  ('STAT', 'resolve'),
  ('STAT', 'morale'),
  ('STAT', 'normalAttackDmg_per'),
  ('STAT', 'plungeDmg'),
  ('STAT', 'plungeAttackSpeed'),
  ('STAT', 'slidingAttackDmg'),
  ('STAT', 'slidingAttackSpeed'),
  ('STAT', 'dmgReceived');

INSERT IGNORE INTO common_code_labels (code_type, code, label) VALUES
  ('STAT', 'attack_per', '공격력%'),
  ('STAT', 'elementAttack_per', '속성 공격력%'),
  ('STAT', 'hp_per', 'HP%'),
  ('STAT', 'defense_per', '방어%'),
  ('STAT', 'shield_per', '실드%'),
  ('STAT', 'damage', '대미지%'),
  ('STAT', 'skillEfficiency', '스킬 효율'),
  ('STAT', 'skillDuration', '스킬 지속'),
  ('STAT', 'skillRange', '스킬 범위'),
  ('STAT', 'skillDmg', '스킬 대미지'),
  ('STAT', 'skillIntensity', '스킬 위력'),
  ('STAT', 'weaponAttack_per', '무기 공격력%'),
  ('STAT', 'slashAttack_per', '베기 공격%'),
  ('STAT', 'spikeAttack_per', '관통 공격%'),
  ('STAT', 'smashAttack_per', '진동 공격%'),
  ('STAT', 'weaponDmg', '무기 대미지'),
  ('STAT', 'explosionRange', '폭발 범위'),
  ('STAT', 'beamLength', '광선 길이'),
  ('STAT', 'reloadSpeed', '장전 속도'),
  ('STAT', 'critRate', '치명타 확률'),
  ('STAT', 'critDamage', '치명타 피해'),
  ('STAT', 'attackSpeed', '공격 속도'),
  ('STAT', 'attackRange', '공격 범위'),
  ('STAT', 'triggerProbability', '발동 확률'),
  ('STAT', 'multishot', '다중 사격'),
  ('STAT', 'magCapacity', '탄창 용량%'),
  ('STAT', 'maxAmmo', '최대 탄약'),
  ('STAT', 'ammoConversionRate', '탄환 전환율'),
  ('STAT', 'resolve', '필사'),
  ('STAT', 'morale', '격양'),
  ('STAT', 'normalAttackDmg_per', '기본 공격 대미지%'),
  ('STAT', 'plungeDmg', '낙하 공격 대미지%'),
  ('STAT', 'plungeAttackSpeed', '낙하 공격 속도'),
  ('STAT', 'slidingAttackDmg', '슬라이딩 공격 대미지%'),
  ('STAT', 'slidingAttackSpeed', '슬라이딩 공격 속도'),
  ('STAT', 'dmgReceived', '받는 대미지');
