import type { Metadata } from "next";
import { getAdminMe } from "@/api/admin";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAdmin = await getAdminMe();
  return (
    <html lang="ko">
      <body className={`bg-[#070b18] text-white`}>{children}</body>
    </html>
  );
}
